apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kafka-topics
  namespace: {{ gitops_namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kafka-topics
    repoURL: https://{{ gitlab_host }}/rhdh/infra-app-of-apps.git
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
